sbatch job_test.sh 0
sbatch job_test.sh 1
sbatch job_test.sh 2
sbatch job_test.sh 3
sbatch job_test.sh 4
sbatch job_test.sh 5
sbatch job_test.sh 6
sbatch job_test.sh 7
sbatch job_test.sh 8
sbatch job_test.sh 9
sbatch job_test.sh 10
sbatch job_test.sh 11
sbatch job_test.sh 12
sbatch job_test.sh 13
sbatch job_test.sh 14
sbatch job_test.sh 15 
sbatch job_test.sh 16
sbatch job_test.sh 17
sbatch job_test.sh 18
sbatch job_test.sh 19
sbatch job_test.sh 20
sbatch job_test.sh 21
sbatch job_test.sh 22
sbatch job_test.sh 23
sbatch job_test.sh 24
sbatch job_test.sh 25 
sbatch job_test.sh 26
sbatch job_test.sh 27
sbatch job_test.sh 28
sbatch job_test.sh 29
sbatch job_test.sh 30
sbatch job_test.sh 31
sbatch job_test.sh 32
sbatch job_test.sh 33
sbatch job_test.sh 34
sbatch job_test.sh 35 
sbatch job_test.sh 36
sbatch job_test.sh 37
sbatch job_test.sh 38
sbatch job_test.sh 39

